spring.application.name=iceops-api-gateway
server.port=8080

# EUREKA
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://iceops-discovery-server:8761/eureka

# DISCOVERY
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true

# ORGANIZATIONS
spring.cloud.gateway.server.webmvc.routes[0].id=organization-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ICEOPS-ORGANIZATION-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/organizations/**

# USERS
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ICEOPS-USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**

# PRODUCTS
spring.cloud.gateway.server.webmvc.routes[2].id=product-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ICEOPS-PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/products/**

# ORDERS
spring.cloud.gateway.server.webmvc.routes[3].id=order-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ICEOPS-ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**

# PAYMENTS
spring.cloud.gateway.server.webmvc.routes[4].id=payment-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ICEOPS-PAYMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/payments/**

# ANALYTICS
spring.cloud.gateway.server.webmvc.routes[5].id=analytics-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ICEOPS-ANALYTICS-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/analytics/**

# ACTUATOR
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# LOGS
logging.level.org.springframework.cloud.gateway=INFO
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1
