import { useEffect, useState } from "react";

import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer
} from "recharts";


import userService from "../../services/userService";
import productService from "../../services/productService";
import orderService from "../../services/orderService";
import paymentService from "../../services/paymentService";


export default function Analytics() {

  const [users, setUsers] = useState([]);
  const [products, setProducts] = useState([]);
  const [orders, setOrders] = useState([]);
  const [payments, setPayments] = useState([]);

  const [loading, setLoading] = useState(true);


  useEffect(() => {
    loadAnalytics();
  }, []);


  async function loadAnalytics() {

    try {

      const [
        usersResponse,
        productsResponse,
        ordersResponse,
        paymentsResponse

      ] = await Promise.all([

        userService.getAll(),
        productService.getAll(),
        orderService.getAll(),
        paymentService.getAll()

      ]);


      setUsers(usersResponse.data || []);
      setProducts(productsResponse.data || []);
      setOrders(ordersResponse.data || []);
      setPayments(paymentsResponse.data || []);


    } catch (error) {

      console.error(
        "Error loading analytics:",
        error
      );

    } finally {

      setLoading(false);

    }

  }


  const totalRevenue = payments.reduce(
    (total,item)=>
      total + Number(item.amount || 0),
    0
  );


  const completedPayments = payments.filter(
    item =>
      String(item.status).toUpperCase() === "COMPLETED"
  ).length;


  const pendingPayments =
    payments.length - completedPayments;



  const summaryData = [

    {
      name:"Orders",
      value:orders.length
    },

    {
      name:"Payments",
      value:payments.length
    },

    {
      name:"Products",
      value:products.length
    }

  ];



  const paymentStatusData = [

    {
      name:"Completed",
      value:completedPayments
    },

    {
      name:"Pending",
      value:pendingPayments
    }

  ];



  const revenueData = [

    {
      name:"Revenue",
      amount:totalRevenue
    }

  ];



  const chartStyle = {

    background:"#21262d",
    border:"1px solid #30363d",
    borderRadius:"8px",
    padding:"20px"

  };



  return (

    <div className="erp-page">


      <h1>Analytics</h1>

      <p>
        Events and operational metrics generated by ICEOPS ERP.
      </p>



      {loading ? (

        <p>
          Loading analytics...
        </p>


      ) : (

        <>


          <div className="erp-grid">


            <div className="erp-card">
              <h3>Total Users</h3>
              <strong>{users.length}</strong>
            </div>


            <div className="erp-card">
              <h3>Total Products</h3>
              <strong>{products.length}</strong>
            </div>


            <div className="erp-card">
              <h3>Total Orders</h3>
              <strong>{orders.length}</strong>
            </div>


            <div className="erp-card">
              <h3>Total Payments</h3>
              <strong>{payments.length}</strong>
            </div>


            <div className="erp-card">
              <h3>Total Revenue</h3>
              <strong>
                ${totalRevenue.toFixed(2)}
              </strong>
            </div>


          </div>



          <h2>Revenue Analytics</h2>


          <div style={chartStyle}>

            <ResponsiveContainer width="100%" height={280}>

              <LineChart data={revenueData}>

                <XAxis dataKey="name" />

                <YAxis />

                <Tooltip />

                <Line
                  type="monotone"
                  dataKey="amount"
                  stroke="#2f81f7"
                  strokeWidth={3}
                />

              </LineChart>

            </ResponsiveContainer>

          </div>



          <h2>Operational Metrics</h2>


          <div style={chartStyle}>

            <ResponsiveContainer width="100%" height={280}>

              <BarChart data={summaryData}>

                <XAxis dataKey="name"/>

                <YAxis/>

                <Tooltip/>

                <Bar
                  dataKey="value"
                  fill="#3fb950"
                />

              </BarChart>

            </ResponsiveContainer>


          </div>



          <h2>Payment Status</h2>


          <div style={chartStyle}>

            <ResponsiveContainer width="100%" height={280}>

              <PieChart>

                <Pie

                  data={paymentStatusData}

                  dataKey="value"

                  nameKey="name"

                  outerRadius={90}

                  label

                >

                  <Cell fill="#3fb950"/>

                  <Cell fill="#d29922"/>


                </Pie>


                <Tooltip/>


              </PieChart>


            </ResponsiveContainer>


          </div>



        </>

      )}


    </div>

  );

}