spring.application.name=ICEOPS-PAYMENT-SERVICE
server.port=8086

# =========================
# MYSQL
# =========================
spring.datasource.url=jdbc:mysql://host.docker.internal:3307/iceops_payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=http://iceops-discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=iceops-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always